/docking_action_server:
  ros__parameters:
    L: 0.3 # meters
    t_step: 0.15
    solver_max_cpu_time: 0.07
    n_horizon: 20
    gains:
      pos: 22.0
      theta: 1.0
      delta: 1.0
    accepted_absolute_errors:
      pos: 0.08
      theta: 0.1
      delta: 0.1
    bounds:
      x_pos: # meters
        lower: 0.0
        upper: 3.0
      y_pos: # meters
        lower: 0.0
        upper: 3.0 
      delta: 
        normalized: 0.5
        radians: 0.4
      v: # meters / sec
        lower: -0.3
        upper: 0.3
      phi: # radians / sec
        lower: -0.7
        upper: 0.7
