/docking_action_server:
  ros__parameters:
    L: 0.3 # meters
    t_step: 0.15
    solver_max_cpu_time: 0.03
    n_horizon: 20
    gains:
      pos: 2.0
      theta: 1.0
      delta: 0.1
    accepted_absolute_errors:
      pos: 0.1
      theta: 0.1
      delta: 0.1
    bounds:
      x_pos: # meters
        lower: 0.0
        upper: 2.2
      y_pos: # meters
        lower: 0.0
        upper: 4.0 
      delta: 
        normalized: 0.5
        radians: 0.4
      v: # meters / sec
        lower: -2.0
        upper: 2.0
      phi: # radians / sec
        lower: -10.0
        upper: 10.0
