# x_pos - unit
# y_pos - unit
# delta - radians
# theta - radians
# v - unit / sec
# phi - radians / sec

/docking_action_server:
  ros__parameters:
    L: 0.3
    t_step: 0.15
    solver_max_cpu_time: 0.03
    n_horizon: 20
    gains:
      pos: 1.0
      theta: 1.0
      delta: 1.0
    accepted_absolute_errors:
      pos: 0.1
      theta: 0.1
      delta: 0.1
    bounds:
      x_pos:
        lower: 0.0
        upper: 2.2
      y_pos:
        lower: 0.0
        upper: 4.0 
      delta:
        lower: -0.5
        upper: 0.5
      v:
        lower: -2.0
        upper: 2.0
      phi:
        lower: -10.0
        upper: 10.0
